export const HOMEPAGECARDS_LOADING = 'HOMEPAGECARDS_LOADING';
export const HOMEPAGECARDS_FAILED = 'HOMEPAGECARDS_FAILED';
export const ADD_HOMEPAGECARDS = 'ADD_HOMEPAGECARDS';
export const HOMEPAGECAROUSEL_LOADING = 'HOMEPAGECAROUSEL_LOADING';
export const HOMEPAGECAROUSEL_FAILED = 'HOMEPAGECAROUSEL_FAILED';
export const ADD_HOMEPAGECAROUSELPAGE = 'ADD_HOMEPAGECAROUSELPAGE';

export const LEARNINGPAGE_LOADING = 'LEARNINGPAGE_LOADING';
export const LEARNINGPAGE_FAILED = 'LEARNINGPAGE_FAILED';
export const ADD_LEARNINGPAGE = 'ADD_LEARNINGPAGE';

export const ONLINEPAGE_LOADING = 'ONLINEPAGE_LOADING';
export const ONLINEPAGE_FAILED = 'ONLINEPAGE_FAILED';
export const ADD_ONLINEPAGE = 'ADD_ONLINEPAGE';
export const ONLINEPAGECARDS_LOADING = 'ONLINEPAGECARDS_LOADING';
export const ONLINEPAGECARDS_FAILED = 'ONLINEPAGECARDS_FAILED';
export const ADD_ONLINEPAGECARDS = 'ADD_ONLINEPAGECARDS';

export const VIRTUALPAGE_LOADING = 'VIRTUALPAGE_LOADING';
export const VIRTUALPAGE_FAILED = 'VIRTUALPAGE_FAILED';
export const ADD_VIRTUALPAGE = 'ADD_VIRTUALPAGE';

export const WHYIDPAGE_LOADING = 'WHYIDPAGE_LOADING';
export const WHYIDPAGE_FAILED = 'WHYIDPAGE_FAILED';
export const ADD_WHYIDPAGE = 'ADD_WHYIDPAGE';

export const REGISTERPAGE_LOADING = 'REGISTERPAGE_LOADING';
export const REGISTERPAGE_FAILED = 'REGISTERPAGE_FAILED';
export const ADD_REGISTERPAGE = 'ADD_REGISTERPAGE';

export const ADD_REGISTRATION = 'ADD_REGISTRATION';
export const ADD_REGISTRATIONS = 'ADD_REGISTRATIONS';
export const REGISTRATIONS_FAILED = 'REGISTRATIONS_FAILED';

export const COURSESPAGE_LOADING = 'COURSESPAGE_LOADING';
export const COURSESPAGE_FAILED = 'COURSESPAGE_FAILED';
export const ADD_COURSESPAGE = 'ADD_COURSESPAGE';
export const COURSESPAGESIDEBAR_LOADING = 'COURSESPAGESIDEBAR_LOADING';
export const COURSESPAGESIDEBAR_FAILED = 'COURSESPAGESIDEBAR_FAILED';
export const ADD_COURSESPAGESIDEBAR = 'ADD_COURSESPAGESIDEBAR';
export const COURSESPAGESEARCHRESULTS_LOADING = 'COURSESPAGESEARCHRESULTS_LOADING';
export const COURSESPAGESEARCHRESULTS_FAILED = 'COURSESPAGESEARCHRESULTS_FAILED';
export const ADD_COURSESPAGESEARCHRESULTS = 'ADD_COURSESPAGESEARCHRESULTS';

export const LOGIN_REQUEST = 'LOGIN_REQUEST';
// export const LOGIN_FB_REQUEST = 'LOGIN_FB_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAILURE = 'LOGOUT_FAILURE';

export const FAVORITES_LOADING = 'FAVORITES_LOADING';
export const FAVORITES_FAILED = 'FAVORITES_FAILED';
export const ADD_FAVORITES = 'ADD_FAVORITES';

export const PARTNERS_LOADING = 'PARTNERS_LOADING';
export const ADD_PARTNERS = 'ADD_PARTNERS';
export const PARTNERS_FAILED = 'PARTNERS_FAILED';